export const sampleRecipes = [
  {
    idMeal: "52940",
    strMeal: "Brown Stew Chicken",
    strCategory: "Chicken",
    strArea: "Jamaican",
    strMealThumb: "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    strInstructions: "Squeeze lime over chicken and rub well. Drain off excess lime juice.\nCombine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour.\nHeat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce.\nLightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces.\nDrain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes.\nMix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.",
    strYoutube: "https://www.youtube.com/watch?v=_gFB1fkNhBc",
    strIngredient1: "Chicken",
    strIngredient2: "Tomato",
    strIngredient3: "Onions",
    strIngredient4: "Garlic",
    strIngredient5: "Lime",
    strMeasure1: "1 whole",
    strMeasure2: "1 chopped",
    strMeasure3: "2 chopped",
    strMeasure4: "2 cloves minced",
    strMeasure5: "1",
    strSource: "http://www.geniuskitchen.com/recipe/authentic-jamaican-brown-stew-chicken-347996"
  },
  {
    idMeal: "53016",
    strMeal: "Chicken Alfredo Primavera",
    strCategory: "Chicken",
    strArea: "Italian",
    strMealThumb: "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    strInstructions: "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.\nWhile the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with salt and add the pasta. Cook according to package directions. Drain and set aside.\nRemove the chicken from the pan and set aside. Add the remaining tablespoon of butter and garlic to the pan and cook for 1 minute. Add the heavy cream, milk, and cream cheese to the pan and bring to a boil. Stir until the cream cheese is fully melted. Add 1/2 cup of the mozzarella and parmesan cheese and stir until melted. Season with salt and pepper.\nAdd the vegetables and cooked pasta to the pan and toss to coat with the sauce. Slice the chicken and add to the pasta. Top with remaining cheese and serve immediately.",
    strYoutube: "https://www.youtube.com/watch?v=qCIbq8HywpQ",
    strIngredient1: "Butter",
    strIngredient2: "Olive Oil",
    strIngredient3: "Chicken",
    strIngredient4: "Salt",
    strIngredient5: "Squash",
    strMeasure1: "2 tablespoons",
    strMeasure2: "2 tablespoons",
    strMeasure3: "1 lb",
    strMeasure4: "To taste",
    strMeasure5: "1 cup",
    strSource: ""
  },
  {
    idMeal: "52795",
    strMeal: "Chicken Handi",
    strCategory: "Chicken",
    strArea: "Indian",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    strInstructions: "Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside.\nTo the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until they become soft. This will take about 5 minutes.\nThen return the fried onion to the pot and stir. Add ginger paste and sauté well.\nNow add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir.\nNext goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes.\nAdd the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This takes about 15 minutes.\nThen add the beaten yogurt keeping the heat on lowest so that the yogurt doesn't split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well.\nFinally add the cream and give a final mix to combine everything well.\nSprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis.",
    strYoutube: "https://www.youtube.com/watch?v=IO0issT0Rmc",
    strIngredient1: "Chicken",
    strIngredient2: "Onion",
    strIngredient3: "Tomatoes",
    strIngredient4: "Garlic",
    strIngredient5: "Ginger paste",
    strMeasure1: "1.2 kg",
    strMeasure2: "5 thinly sliced",
    strMeasure3: "2 finely chopped",
    strMeasure4: "8 cloves chopped",
    strMeasure5: "1 tbsp",
    strSource: "https://www.relishthebite.com/chicken-handi/"
  },
  {
    idMeal: "52772",
    strMeal: "Teriyaki Chicken Casserole",
    strCategory: "Chicken",
    strArea: "Japanese",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    strInstructions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the pan using two forks.\nMeanwhile, steam or cook the vegetables according to package directions.\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
    strIngredient1: "soy sauce",
    strIngredient2: "water",
    strIngredient3: "brown sugar",
    strIngredient4: "ground ginger",
    strIngredient5: "garlic",
    strMeasure1: "3/4 cup",
    strMeasure2: "1/2 cup",
    strMeasure3: "1/4 cup",
    strMeasure4: "1/2 teaspoon",
    strMeasure5: "1/2 teaspoon",
    strSource: "https://www.budgetbytes.com/2017/02/teriyaki-chicken-casserole/"
  }
];